version: "3.2"
services:
  frontend:
    build: ./client
    networks:
      - frontend
    ports:
      - "30001:3000"
    links:
      - backend
    container_name: reactjsFE
  backend:
    build: .
    networks:
      - backend
      - frontend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=moeuser
      - MYSQL_PASS=moepass
      - MYSQL_DB=moe_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8080:6060"
    links:
      - mysqld
    container_name: nodejsBE
  mysqld:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass
      - MYSQL_DATABASE=moe_db
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqld
    links:
      - mysqld
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
