version: "3.2"
services:
  frontend:
    build: ./client
    networks:
      - frontend
    ports:
      - "30001:3000"
    links:
      - backend
    container_name: reactjsFE
  backend:
    build: .
    networks:
      - backend
      - frontend
    environment:
      - POSTGRES_DB=boardgamecomplexitycompare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - ./www/:/var/www/html/
    depends_on:
      - db
    ports:
      - "8080:6060"
    links:
      - db
    container_name: nodejsBE
  db:
    image: postgres:12
    networks:
      - backend
    environment:
      - POSTGRES_DB=boardgamecomplexitycompare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_sql
networks:
  frontend:
  backend:
